package co.edu.unbosque.entrecolbackend.service;

import java.util.concurrent.ThreadLocalRandom;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

import jakarta.mail.MessagingException;
import jakarta.mail.internet.MimeMessage;

@Service
public class EmailService {

	@Autowired
	private JavaMailSender javaMailSender;

	public void sendWelcomeEmail(String to) {
		MimeMessage message = javaMailSender.createMimeMessage();
		MimeMessageHelper helper = new MimeMessageHelper(message, "utf-8");
		try {
			helper.setTo(to);
			helper.setSubject("Welcome to Entrecol+");

			// Utiliza HTML para dar estilo al correo electrónico
			String htmlMsg = "<!DOCTYPE html>\r\n"
					+ "<html xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\" lang=\"en\">\r\n"
					+ "\r\n" + "<head>\r\n" + "	<title></title>\r\n"
					+ "	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n"
					+ "	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch><o:AllowPNG/></o:OfficeDocumentSettings></xml><![endif]--><!--[if !mso]><!-->\r\n"
					+ "	<link href=\"https://fonts.googleapis.com/css?family=Montserrat\" rel=\"stylesheet\" type=\"text/css\"><!--<![endif]-->\r\n"
					+ "	<style>\r\n" + "		* {\r\n" + "			box-sizing: border-box;\r\n" + "		}\r\n"
					+ "\r\n" + "		body {\r\n" + "			margin: 0;\r\n" + "			padding: 0;\r\n"
					+ "		}\r\n" + "\r\n" + "		a[x-apple-data-detectors] {\r\n"
					+ "			color: inherit !important;\r\n" + "			text-decoration: inherit !important;\r\n"
					+ "		}\r\n" + "\r\n" + "		#MessageViewBody a {\r\n" + "			color: inherit;\r\n"
					+ "			text-decoration: none;\r\n" + "		}\r\n" + "\r\n" + "		p {\r\n"
					+ "			line-height: inherit\r\n" + "		}\r\n" + "\r\n" + "		.desktop_hide,\r\n"
					+ "		.desktop_hide table {\r\n" + "			mso-hide: all;\r\n" + "			display: none;\r\n"
					+ "			max-height: 0px;\r\n" + "			overflow: hidden;\r\n" + "		}\r\n" + "\r\n"
					+ "		.image_block img+div {\r\n" + "			display: none;\r\n" + "		}\r\n" + "\r\n"
					+ "		sup,\r\n" + "		sub {\r\n" + "			font-size: 75%;\r\n"
					+ "			line-height: 0;\r\n" + "		}\r\n" + "\r\n"
					+ "		.menu_block.desktop_hide .menu-links span {\r\n" + "			mso-hide: all;\r\n"
					+ "		}\r\n" + "\r\n" + "		@media (max-width:675px) {\r\n" + "\r\n"
					+ "			.desktop_hide table.icons-inner,\r\n"
					+ "			.social_block.desktop_hide .social-table {\r\n"
					+ "				display: inline-block !important;\r\n" + "			}\r\n" + "\r\n"
					+ "			.icons-inner {\r\n" + "				text-align: center;\r\n" + "			}\r\n"
					+ "\r\n" + "			.icons-inner td {\r\n" + "				margin: 0 auto;\r\n"
					+ "			}\r\n" + "\r\n" + "			.menu-checkbox[type=checkbox]~.menu-links {\r\n"
					+ "				display: none !important;\r\n" + "				padding: 5px 0;\r\n"
					+ "			}\r\n" + "\r\n"
					+ "			.menu-checkbox[type=checkbox]:checked~.menu-trigger .menu-open,\r\n"
					+ "			.menu-checkbox[type=checkbox]~.menu-links span.sep {\r\n"
					+ "				display: none !important;\r\n" + "			}\r\n" + "\r\n"
					+ "			.menu-checkbox[type=checkbox]:checked~.menu-links,\r\n"
					+ "			.menu-checkbox[type=checkbox]~.menu-trigger {\r\n"
					+ "				display: block !important;\r\n" + "				max-width: none !important;\r\n"
					+ "				max-height: none !important;\r\n"
					+ "				font-size: inherit !important;\r\n" + "			}\r\n" + "\r\n"
					+ "			.menu-checkbox[type=checkbox]~.menu-links>a,\r\n"
					+ "			.menu-checkbox[type=checkbox]~.menu-links>span.label {\r\n"
					+ "				display: block !important;\r\n" + "				text-align: center;\r\n"
					+ "			}\r\n" + "\r\n"
					+ "			.menu-checkbox[type=checkbox]:checked~.menu-trigger .menu-close {\r\n"
					+ "				display: block !important;\r\n" + "			}\r\n" + "\r\n"
					+ "			.mobile_hide {\r\n" + "				display: none;\r\n" + "			}\r\n" + "\r\n"
					+ "			.row-content {\r\n" + "				width: 100% !important;\r\n" + "			}\r\n"
					+ "\r\n" + "			.stack .column {\r\n" + "				width: 100%;\r\n"
					+ "				display: block;\r\n" + "			}\r\n" + "\r\n" + "			.mobile_hide {\r\n"
					+ "				min-height: 0;\r\n" + "				max-height: 0;\r\n"
					+ "				max-width: 0;\r\n" + "				overflow: hidden;\r\n"
					+ "				font-size: 0px;\r\n" + "			}\r\n" + "\r\n" + "			.desktop_hide,\r\n"
					+ "			.desktop_hide table {\r\n" + "				display: table !important;\r\n"
					+ "				max-height: none !important;\r\n" + "			}\r\n" + "		}\r\n" + "\r\n"
					+ "		#memu-r0c1m1:checked~.menu-links {\r\n"
					+ "			background-color: undefined !important;\r\n" + "		}\r\n" + "\r\n"
					+ "		#memu-r0c1m1:checked~.menu-links a,\r\n"
					+ "		#memu-r0c1m1:checked~.menu-links span {\r\n" + "			color: #000000 !important;\r\n"
					+ "		}\r\n"
					+ "	</style><!--[if mso ]><style>sup, sub { font-size: 100% !important; } sup { mso-text-raise:10% } sub { mso-text-raise:-10% }</style> <![endif]-->\r\n"
					+ "</head>\r\n" + "\r\n"
					+ "<body class=\"body\" style=\"margin: 0; padding: 0; -webkit-text-size-adjust: none; text-size-adjust: none; background-color: #0a0a0a;\">\r\n"
					+ "	<table class=\"nl-container\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #0a0a0a;\">\r\n"
					+ "		<tbody>\r\n" + "			<tr>\r\n" + "				<td>\r\n"
					+ "					<table class=\"row row-1\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #0a0a0a;\">\r\n"
					+ "						<tbody>\r\n" + "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #0a0a0a; color: #000000; width: 655px; margin: 0 auto;\" width=\"655\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"41.666666666666664%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 10px; padding-left: 20px; padding-right: 20px; padding-top: 15px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"image_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"width:100%;padding-right:0px;padding-left:0px;\">\r\n"
					+ "																<div class=\"alignment\" align=\"center\" style=\"line-height:10px\">\r\n"
					+ "																	<div style=\"max-width: 116.458px;\"><a href=\"http://www.example.com/\" target=\"_blank\" style=\"outline:none\" tabindex=\"-1\"><img src=\"https://ed5bf4f71f.imgdist.com/pub/bfra/qahjrtlh/zep/e62/gec/Colplus.png\" style=\"display: block; height: auto; border: 0; width: 100%;\" width=\"116.458\" alt=\"Your-Logo\" title=\"Your-Logo\" height=\"auto\"></a></div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "												<td class=\"column column-2\" width=\"58.333333333333336%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 20px; padding-left: 20px; padding-right: 20px; padding-top: 25px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<div class=\"spacer_block block-1\" style=\"height:25px;line-height:25px;font-size:1px;\">&#8202;</div>\r\n"
					+ "													<table class=\"menu_block block-2\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"color:#ffffff;font-family:inherit;font-size:15px;text-align:center;\">\r\n"
					+ "																<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "																	<tr>\r\n"
					+ "																		<td class=\"alignment\" style=\"text-align:center;font-size:0px;\"><!--[if !mso]><!--><input class=\"menu-checkbox\" id=\"memu-r0c1m1\" type=\"checkbox\" style=\"display:none !important;max-height:0;visibility:hidden;\"><!--<![endif]-->\r\n"
					+ "																			<div class=\"menu-trigger\" style=\"display:none;max-height:0px;max-width:0px;font-size:0px;overflow:hidden;\"><label class=\"menu-label\" for=\"memu-r0c1m1\" style=\"height: 36px; width: 36px; display: inline-block; cursor: pointer; mso-hide: all; user-select: none; align: center; text-align: center; color: #000000; text-decoration: none; background-color: undefined; border-radius: 50%;\"><span class=\"menu-open\" style=\"word-break: break-word; mso-hide: all; font-size: 26px; line-height: 31.5px;\">☰</span><span class=\"menu-close\" style=\"word-break: break-word; display: none; mso-hide: all; font-size: 26px; line-height: 36px;\">✕</span></label></div>\r\n"
					+ "																			<div class=\"menu-links\"><!--[if mso]><table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" style=\"\"><tr style=\"text-align:center;\"><![endif]--><!--[if mso]><td style=\"padding-top:10px;padding-right:5px;padding-bottom:;padding-left:5px\"><![endif]--><a href=\"http://www.example.com/\" target=\"_self\" style=\"mso-hide:false;padding-top:10px;padding-bottom:undefined;padding-left:5px;padding-right:5px;display:inline-block;color:#ffffff;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;font-size:15px;text-decoration:none;letter-spacing:normal;\">Registros</a><!--[if mso]></td><td><![endif]--><span class=\"sep\" style=\"word-break: break-word; font-size: 15px; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; color: #ffffff;\">| </span><!--[if mso]></td><![endif]--><!--[if mso]><td style=\"padding-top:10px;padding-right:5px;padding-bottom:;padding-left:5px\"><![endif]--><a href=\"http://www.example.com/\" target=\"_self\" style=\"mso-hide:false;padding-top:10px;padding-bottom:undefined;padding-left:5px;padding-right:5px;display:inline-block;color:#ffffff;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;font-size:15px;text-decoration:none;letter-spacing:normal;\">Entretenimiento</a><!--[if mso]></td><td><![endif]--><span class=\"sep\" style=\"word-break: break-word; font-size: 15px; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; color: #ffffff;\">| </span><!--[if mso]></td><![endif]--><!--[if mso]><td style=\"padding-top:10px;padding-right:5px;padding-bottom:;padding-left:5px\"><![endif]--><a href=\"http://www.example.com/\" target=\"_self\" style=\"mso-hide:false;padding-top:10px;padding-bottom:undefined;padding-left:5px;padding-right:5px;display:inline-block;color:#ffffff;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;font-size:15px;text-decoration:none;letter-spacing:normal;\">Novedades</a><!--[if mso]></td><![endif]--><!--[if mso]></tr></table><![endif]--></div>\r\n"
					+ "																		</td>\r\n"
					+ "																	</tr>\r\n"
					+ "																</table>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n" + "								</td>\r\n"
					+ "							</tr>\r\n" + "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-2\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "						<tbody>\r\n" + "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #0a0a0a; color: #000000; background-position: top center; width: 655px; margin: 0 auto;\" width=\"655\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 20px; padding-left: 10px; padding-right: 10px; padding-top: 20px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"image_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"width:100%;\">\r\n"
					+ "																<div class=\"alignment\" align=\"center\" style=\"line-height:10px\">\r\n"
					+ "																	<div style=\"max-width: 635px;\"><a href=\"www.example.com\" target=\"_blank\" style=\"outline:none\" tabindex=\"-1\"><img src=\"https://ed5bf4f71f.imgdist.com/pub/bfra/qahjrtlh/ci4/12m/j6y/EntreCol%2B%20Solutions%20%281%29.png\" style=\"display: block; height: auto; border: 0; width: 100%;\" width=\"635\" alt=\"cyber-monday\" title=\"cyber-monday\" height=\"auto\"></a></div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n" + "								</td>\r\n"
					+ "							</tr>\r\n" + "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-3\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-position: top center;\">\r\n"
					+ "						<tbody>\r\n" + "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #0a0a0a; color: #000000; width: 655px; margin: 0 auto;\" width=\"655\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 40px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"heading_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"text-align:center;width:100%;\">\r\n"
					+ "																<h1 style=\"margin: 0; color: #ffffff; direction: ltr; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; font-size: 40px; font-weight: 700; letter-spacing: normal; line-height: 120%; text-align: center; margin-top: 0; margin-bottom: 0; mso-line-height-alt: 48px;\"><span class=\"tinyMce-placeholder\" style=\"word-break: break-word;\">¡Bienvenido!</span></h1>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "													<table class=\"paragraph_block block-2\" width=\"100%\" border=\"0\" cellpadding=\"20\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\">\r\n"
					+ "																<div style=\"color:#ffffff;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;font-size:16px;font-weight:400;line-height:150%;text-align:center;mso-line-height-alt:24px;\">\r\n"
					+ "																	<p style=\"margin: 0; word-break: break-word;\">Gracias por unirte a EntreCOL+, la plataforma líder de entretenimiento multimedia en Colombia. Estamos encantados de tenerte a bordo y queremos darte la bienvenida presentándote los beneficios exclusivos que ahora tienes a tu disposición.</p>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "													<div class=\"spacer_block block-3\" style=\"height:25px;line-height:25px;font-size:1px;\">&#8202;</div>\r\n"
					+ "													<table class=\"heading_block block-4\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"text-align:center;width:100%;\">\r\n"
					+ "																<h2 style=\"margin: 0; color: #f21c25; direction: ltr; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; font-size: 30px; font-weight: 400; letter-spacing: normal; line-height: 120%; text-align: center; margin-top: 0; margin-bottom: 0; mso-line-height-alt: 36px;\"><span class=\"tinyMce-placeholder\" style=\"word-break: break-word;\">¿Qué puedes encontrar?</span></h2>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n" + "								</td>\r\n"
					+ "							</tr>\r\n" + "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-4\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "						<tbody>\r\n" + "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #0a0a0a; color: #000000; width: 655px; margin: 0 auto;\" width=\"655\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"50%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 20px; padding-left: 10px; padding-right: 10px; padding-top: 15px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"image_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"10\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\">\r\n"
					+ "																<div class=\"alignment\" align=\"center\" style=\"line-height:10px\">\r\n"
					+ "																	<div style=\"max-width: 76.875px;\"><img src=\"https://ed5bf4f71f.imgdist.com/pub/bfra/qahjrtlh/8s2/qmq/rkm/icons8-entertainment-64.png\" style=\"display: block; height: auto; border: 0; width: 100%;\" width=\"76.875\" alt=\"personal-icon\" title=\"personal-icon\" height=\"auto\"></div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "													<table class=\"heading_block block-2\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"text-align:center;width:100%;\">\r\n"
					+ "																<h1 style=\"margin: 0; color: #ffffff; direction: ltr; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; font-size: 30px; font-weight: normal; letter-spacing: normal; line-height: 120%; text-align: center; margin-top: 0; margin-bottom: 0; mso-line-height-alt: 36px;\"><strong>Entretenimiento</strong></h1>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "													<div class=\"spacer_block block-3\" style=\"height:30px;line-height:30px;font-size:1px;\">&#8202;</div>\r\n"
					+ "													<table class=\"paragraph_block block-4\" width=\"100%\" border=\"0\" cellpadding=\"20\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\">\r\n"
					+ "																<div style=\"color:#ffffff;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;font-size:16px;line-height:150%;text-align:center;mso-line-height-alt:24px;\">\r\n"
					+ "																	<p style=\"margin: 0; word-break: break-word;\">Disfruta de nuestra biblioteca con más de 65,000 películas de todos los géneros y más de 45,000 libros.&nbsp;</p>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "												<td class=\"column column-2\" width=\"50%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 20px; padding-left: 10px; padding-right: 10px; padding-top: 15px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"image_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"10\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\">\r\n"
					+ "																<div class=\"alignment\" align=\"center\" style=\"line-height:10px\">\r\n"
					+ "																	<div style=\"max-width: 76.875px;\"><img src=\"https://ed5bf4f71f.imgdist.com/pub/bfra/qahjrtlh/t14/nzy/utb/icons8-employee-80.png\" style=\"display: block; height: auto; border: 0; width: 100%;\" width=\"76.875\" alt=\"community-icon\" title=\"community-icon\" height=\"auto\"></div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "													<table class=\"heading_block block-2\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"text-align:center;width:100%;\">\r\n"
					+ "																<h1 style=\"margin: 0; color: #ffffff; direction: ltr; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; font-size: 30px; font-weight: normal; letter-spacing: normal; line-height: 120%; text-align: center; margin-top: 0; margin-bottom: 0; mso-line-height-alt: 36px;\"><strong>Entretenimiento</strong></h1>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "													<table class=\"paragraph_block block-3\" width=\"100%\" border=\"0\" cellpadding=\"20\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\">\r\n"
					+ "																<div style=\"color:#ffffff;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;font-size:16px;line-height:150%;text-align:center;mso-line-height-alt:24px;\">\r\n"
					+ "																	<p style=\"margin: 0; word-break: break-word;\">Accede de forma rápida a tus detalles salariales, incluyendo un desglose detallado de tus aportes a pensión, EPS, y deducciones. Recibirás un reporte mensual que puedes revisar en cualquier momento.</p>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n" + "								</td>\r\n"
					+ "							</tr>\r\n" + "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-5\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "						<tbody>\r\n" + "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #0a0a0a; color: #000000; width: 655px; margin: 0 auto;\" width=\"655\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 30px; padding-top: 40px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"image_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"width:100%;\">\r\n"
					+ "																<div class=\"alignment\" align=\"center\" style=\"line-height:10px\">\r\n"
					+ "																	<div style=\"max-width: 655px;\"><a href=\"www.example.com\" target=\"_blank\" style=\"outline:none\" tabindex=\"-1\"><img src=\"https://ed5bf4f71f.imgdist.com/pub/bfra/qahjrtlh/6pk/lca/2pq/EntreCol%2B%20Solutions%20%282%29.png\" style=\"display: block; height: auto; border: 0; width: 100%;\" width=\"655\" alt=\"divider-song\" title=\"divider-song\" height=\"auto\"></a></div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n" + "								</td>\r\n"
					+ "							</tr>\r\n" + "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-6\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "						<tbody>\r\n" + "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #0a0a0a; color: #000000; width: 655px; margin: 0 auto;\" width=\"655\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 40px; padding-left: 20px; padding-right: 20px; padding-top: 20px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"heading_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"padding-top:10px;text-align:center;width:100%;\">\r\n"
					+ "																<h2 style=\"margin: 0; color: #ffffff; direction: ltr; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; font-size: 42px; font-weight: normal; letter-spacing: 2px; line-height: 120%; text-align: center; margin-top: 0; margin-bottom: 0; mso-line-height-alt: 50.4px;\">🎯 <strong>Soporte Total</strong></h2>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "													<table class=\"paragraph_block block-2\" width=\"100%\" border=\"0\" cellpadding=\"20\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\">\r\n"
					+ "																<div style=\"color:#ffffff;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;font-size:16px;line-height:150%;text-align:center;mso-line-height-alt:24px;\">\r\n"
					+ "																	<p style=\"margin: 0; word-break: break-word;\">Si tienes alguna duda o necesitas asistencia, nuestro equipo de soporte está aquí para ayudarte.</p>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n" + "								</td>\r\n"
					+ "							</tr>\r\n" + "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-7\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "						<tbody>\r\n" + "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #0a0a0a; color: #000000; width: 655px; margin: 0 auto;\" width=\"655\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 40px; padding-left: 20px; padding-right: 20px; padding-top: 60px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"heading_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"padding-top:10px;text-align:center;width:100%;\">\r\n"
					+ "																<h2 style=\"margin: 0; color: #ffffff; direction: ltr; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; font-size: 42px; font-weight: 700; letter-spacing: 2px; line-height: 120%; text-align: center; margin-top: 0; margin-bottom: 0; mso-line-height-alt: 50.4px;\">Equipo EntreCOL+</h2>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "													<table class=\"paragraph_block block-2\" width=\"100%\" border=\"0\" cellpadding=\"20\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\">\r\n"
					+ "																<div style=\"color:#ffffff;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;font-size:16px;line-height:150%;text-align:center;mso-line-height-alt:24px;\">\r\n"
					+ "																	<p style=\"margin: 0; word-break: break-word;\">Gracias por ser parte de esta comunidad y confiar en EntreCOL+. Estamos seguros de que disfrutarás de todas las ventajas y beneficios que te ofrecemos.</p>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n" + "								</td>\r\n"
					+ "							</tr>\r\n" + "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-8\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #000000;\">\r\n"
					+ "						<tbody>\r\n" + "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #0a0a0a; color: #000000; width: 655px; margin: 0 auto;\" width=\"655\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 20px; padding-top: 40px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"image_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"padding-bottom:15px;padding-left:10px;width:100%;padding-right:0px;\">\r\n"
					+ "																<div class=\"alignment\" align=\"center\" style=\"line-height:10px\">\r\n"
					+ "																	<div style=\"max-width: 65.5px;\"><a href=\"http://www.example.com/\" target=\"_blank\" style=\"outline:none\" tabindex=\"-1\"><img src=\"https://ed5bf4f71f.imgdist.com/pub/bfra/qahjrtlh/zep/e62/gec/Colplus.png\" style=\"display: block; height: auto; border: 0; width: 100%;\" width=\"65.5\" alt=\"Your-Logo\" title=\"Your-Logo\" height=\"auto\"></a></div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "													<table class=\"social_block block-2\" width=\"100%\" border=\"0\" cellpadding=\"10\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\">\r\n"
					+ "																<div class=\"alignment\" align=\"center\">\r\n"
					+ "																	<table class=\"social-table\" width=\"156px\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; display: inline-block;\">\r\n"
					+ "																		<tr>\r\n"
					+ "																			<td style=\"padding:0 10px 0 10px;\"><a href=\"https://www.facebook.com\" target=\"_blank\"><img src=\"https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-circle-white/facebook@2x.png\" width=\"32\" height=\"auto\" alt=\"Facebook\" title=\"facebook\" style=\"display: block; height: auto; border: 0;\"></a></td>\r\n"
					+ "																			<td style=\"padding:0 10px 0 10px;\"><a href=\"https://www.twitter.com\" target=\"_blank\"><img src=\"https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-circle-white/twitter@2x.png\" width=\"32\" height=\"auto\" alt=\"Twitter\" title=\"twitter\" style=\"display: block; height: auto; border: 0;\"></a></td>\r\n"
					+ "																			<td style=\"padding:0 10px 0 10px;\"><a href=\"https://www.instagram.com\" target=\"_blank\"><img src=\"https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-circle-white/instagram@2x.png\" width=\"32\" height=\"auto\" alt=\"Instagram\" title=\"instagram\" style=\"display: block; height: auto; border: 0;\"></a></td>\r\n"
					+ "																		</tr>\r\n"
					+ "																	</table>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "													<table class=\"paragraph_block block-3\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"padding-bottom:15px;padding-left:10px;padding-right:10px;padding-top:15px;\">\r\n"
					+ "																<div style=\"color:#dedede;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;font-size:14px;line-height:120%;text-align:center;mso-line-height-alt:16.8px;\">\r\n"
					+ "																	<p style=\"margin: 0; word-break: break-word;\"><em>2024 © All rights reserved</em></p>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n" + "								</td>\r\n"
					+ "							</tr>\r\n" + "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-9\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ffffff;\">\r\n"
					+ "						<tbody>\r\n" + "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #0a0a0a; color: #000000; width: 655px; margin: 0 auto;\" width=\"655\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"icons_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; text-align: center; line-height: 0;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"vertical-align: middle; color: #1e0e4b; font-family: 'Inter', sans-serif; font-size: 15px; padding-bottom: 5px; padding-top: 5px; text-align: center;\"><!--[if vml]><table align=\"center\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"display:inline-block;padding-left:0px;padding-right:0px;mso-table-lspace: 0pt;mso-table-rspace: 0pt;\"><![endif]-->\r\n"
					+ "																<!--[if !vml]><!-->\r\n"
					+ "																<table class=\"icons-inner\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; display: inline-block; padding-left: 0px; padding-right: 0px;\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\"><!--<![endif]-->\r\n"
					+ "																	<tr>\r\n"
					+ "																		<td style=\"vertical-align: middle; text-align: center; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 6px;\"><a href=\"http://designedwithbeefree.com/\" target=\"_blank\" style=\"text-decoration: none;\"><img class=\"icon\" alt=\"Beefree Logo\" src=\"https://d1oco4z2z1fhwp.cloudfront.net/assets/Beefree-logo.png\" height=\"auto\" width=\"34\" align=\"center\" style=\"display: block; height: auto; margin: 0 auto; border: 0;\"></a></td>\r\n"
					+ "																		<td style=\"font-family: 'Inter', sans-serif; font-size: 15px; font-weight: undefined; color: #1e0e4b; vertical-align: middle; letter-spacing: undefined; text-align: center; line-height: normal;\"><a href=\"http://designedwithbeefree.com/\" target=\"_blank\" style=\"color: #1e0e4b; text-decoration: none;\">Designed with Beefree</a></td>\r\n"
					+ "																	</tr>\r\n"
					+ "																</table>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n" + "								</td>\r\n"
					+ "							</tr>\r\n" + "						</tbody>\r\n"
					+ "					</table>\r\n" + "				</td>\r\n" + "			</tr>\r\n"
					+ "		</tbody>\r\n" + "	</table><!-- End -->\r\n" + "</body>\r\n" + "\r\n" + "</html>";
			helper.setText(htmlMsg, true); // Indica que el texto es HTML

			javaMailSender.send(message);
		} catch (MessagingException e) {
			e.printStackTrace();
		}
	}

	public void sendUpdateEmail(String to) {
		MimeMessage message = javaMailSender.createMimeMessage();
		MimeMessageHelper helper = new MimeMessageHelper(message);
		try {
			helper.setTo(to);
			helper.setSubject("Information updated successfully");
			helper.setText("Your information has been updated, if it was not you call the admin");

			javaMailSender.send(message);
		} catch (MessagingException e) {
			e.printStackTrace();
			// Maneja la excepción apropiadamente
		}
	}

	public void sendFileReport(String to, String fileReport) {
		MimeMessage message = javaMailSender.createMimeMessage();
		MimeMessageHelper helper = new MimeMessageHelper(message);
		try {
			helper.setTo(to);
			helper.setText(fileReport);

			javaMailSender.send(message);
		} catch (MessagingException e) {
			e.printStackTrace();
		}
	}

	public String recoverPasswordEmail(String to) {

		MimeMessage message = javaMailSender.createMimeMessage();
		MimeMessageHelper helper = new MimeMessageHelper(message);

		try {
			helper.setTo(to);
			helper.setSubject("Correct login code");
			String code = randomString();

			String htmlMessage = "<!DOCTYPE html>\r\n"
					+ "<html xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\" lang=\"en\">\r\n"
					+ "\r\n" + "<head>\r\n" + "	<title></title>\r\n"
					+ "	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n"
					+ "	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch><o:AllowPNG/></o:OfficeDocumentSettings></xml><![endif]--><!--[if !mso]><!-->\r\n"
					+ "	<link href=\"https://fonts.googleapis.com/css?family=Montserrat\" rel=\"stylesheet\" type=\"text/css\"><!--<![endif]-->\r\n"
					+ "	<style>\r\n" + "		* {\r\n" + "			box-sizing: border-box;\r\n" + "		}\r\n"
					+ "\r\n" + "		body {\r\n" + "			margin: 0;\r\n" + "			padding: 0;\r\n"
					+ "		}\r\n" + "\r\n" + "		a[x-apple-data-detectors] {\r\n"
					+ "			color: inherit !important;\r\n" + "			text-decoration: inherit !important;\r\n"
					+ "		}\r\n" + "\r\n" + "		#MessageViewBody a {\r\n" + "			color: inherit;\r\n"
					+ "			text-decoration: none;\r\n" + "		}\r\n" + "\r\n" + "		p {\r\n"
					+ "			line-height: inherit\r\n" + "		}\r\n" + "\r\n" + "		.desktop_hide,\r\n"
					+ "		.desktop_hide table {\r\n" + "			mso-hide: all;\r\n" + "			display: none;\r\n"
					+ "			max-height: 0px;\r\n" + "			overflow: hidden;\r\n" + "		}\r\n" + "\r\n"
					+ "		.image_block img+div {\r\n" + "			display: none;\r\n" + "		}\r\n" + "\r\n"
					+ "		sup,\r\n" + "		sub {\r\n" + "			font-size: 75%;\r\n"
					+ "			line-height: 0;\r\n" + "		}\r\n" + "\r\n" + "		@media (max-width:675px) {\r\n"
					+ "\r\n" + "			.desktop_hide table.icons-inner,\r\n"
					+ "			.social_block.desktop_hide .social-table {\r\n"
					+ "				display: inline-block !important;\r\n" + "			}\r\n" + "\r\n"
					+ "			.icons-inner {\r\n" + "				text-align: center;\r\n" + "			}\r\n"
					+ "\r\n" + "			.icons-inner td {\r\n" + "				margin: 0 auto;\r\n"
					+ "			}\r\n" + "\r\n" + "			.mobile_hide {\r\n" + "				display: none;\r\n"
					+ "			}\r\n" + "\r\n" + "			.row-content {\r\n"
					+ "				width: 100% !important;\r\n" + "			}\r\n" + "\r\n"
					+ "			.stack .column {\r\n" + "				width: 100%;\r\n"
					+ "				display: block;\r\n" + "			}\r\n" + "\r\n" + "			.mobile_hide {\r\n"
					+ "				min-height: 0;\r\n" + "				max-height: 0;\r\n"
					+ "				max-width: 0;\r\n" + "				overflow: hidden;\r\n"
					+ "				font-size: 0px;\r\n" + "			}\r\n" + "\r\n" + "			.desktop_hide,\r\n"
					+ "			.desktop_hide table {\r\n" + "				display: table !important;\r\n"
					+ "				max-height: none !important;\r\n" + "			}\r\n" + "		}\r\n"
					+ "	</style><!--[if mso ]><style>sup, sub { font-size: 100% !important; } sup { mso-text-raise:10% } sub { mso-text-raise:-10% }</style> <![endif]-->\r\n"
					+ "</head>\r\n" + "\r\n"
					+ "<body class=\"body\" style=\"margin: 0; background-color: #0a0a0a; padding: 0; -webkit-text-size-adjust: none; text-size-adjust: none;\">\r\n"
					+ "	<table class=\"nl-container\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #0a0a0a;\">\r\n"
					+ "		<tbody>\r\n" + "			<tr>\r\n" + "				<td>\r\n"
					+ "					<table class=\"row row-1\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "						<tbody>\r\n" + "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #0a0a0a; border-radius: 0; color: #000000; width: 655px; margin: 0 auto;\" width=\"655\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"25%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"image_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"width:100%;padding-right:0px;padding-left:0px;\">\r\n"
					+ "																<div class=\"alignment\" align=\"center\" style=\"line-height:10px\">\r\n"
					+ "																	<div style=\"max-width: 106px;\"><img src=\"https://ed5bf4f71f.imgdist.com/pub/bfra/qahjrtlh/zep/e62/gec/Colplus.png\" style=\"display: block; height: auto; border: 0; width: 100%;\" width=\"106\" alt title height=\"auto\"></div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "												<td class=\"column column-2\" width=\"75%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<div class=\"spacer_block block-1\" style=\"height:25px;line-height:25px;font-size:1px;\">&#8202;</div>\r\n"
					+ "													<table class=\"heading_block block-2\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"text-align:center;width:100%;\">\r\n"
					+ "																<h1 style=\"margin: 0; color: #ffffff; direction: ltr; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; font-size: 40px; font-weight: 700; letter-spacing: normal; line-height: 120%; text-align: center; margin-top: 0; margin-bottom: 0; mso-line-height-alt: 48px;\"><span class=\"tinyMce-placeholder\" style=\"word-break: break-word;\">EntreCol+</span></h1>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n" + "								</td>\r\n"
					+ "							</tr>\r\n" + "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-2\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "						<tbody>\r\n" + "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #0a0a0a; border-radius: 0; color: #000000; width: 655px; margin: 0 auto;\" width=\"655\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"25%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"image_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"width:100%;\">\r\n"
					+ "																<div class=\"alignment\" align=\"center\" style=\"line-height:10px\">\r\n"
					+ "																	<div style=\"max-width: 163.75px;\"><a href=\"www.example.com\" target=\"_blank\" style=\"outline:none\" tabindex=\"-1\"><img src=\"https://ed5bf4f71f.imgdist.com/pub/bfra/qahjrtlh/6pk/lca/2pq/EntreCol%2B%20Solutions%20%282%29.png\" style=\"display: block; height: auto; border: 0; width: 100%;\" width=\"163.75\" alt=\"divider-song\" title=\"divider-song\" height=\"auto\"></a></div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "												<td class=\"column column-2\" width=\"75%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"heading_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"text-align:center;width:100%;\">\r\n"
					+ "																<h1 style=\"margin: 0; color: #ffffff; direction: ltr; font-family: Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif; font-size: 40px; font-weight: 700; letter-spacing: normal; line-height: 120%; text-align: center; margin-top: 0; margin-bottom: 0; mso-line-height-alt: 48px;\"><span class=\"tinyMce-placeholder\" style=\"word-break: break-word;\">Este es tu Código</span></h1>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "													<table class=\"paragraph_block block-2\" width=\"100%\" border=\"0\" cellpadding=\"20\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\">\r\n"
					+ "																<div style=\"color:#ffffff;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;font-size:16px;font-weight:400;line-height:150%;text-align:center;mso-line-height-alt:24px;\">\r\n"
					+ "																	<p style=\"margin: 0;\">-&gt;"
					+ code + "&lt;-</p>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n" + "								</td>\r\n"
					+ "							</tr>\r\n" + "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-3\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #000000;\">\r\n"
					+ "						<tbody>\r\n" + "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #0a0a0a; color: #000000; width: 655px; margin: 0 auto;\" width=\"655\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 20px; padding-top: 40px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"image_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"padding-bottom:15px;padding-left:10px;width:100%;padding-right:0px;\">\r\n"
					+ "																<div class=\"alignment\" align=\"center\" style=\"line-height:10px\">\r\n"
					+ "																	<div style=\"max-width: 65.5px;\"><a href=\"http://www.example.com/\" target=\"_blank\" style=\"outline:none\" tabindex=\"-1\"><img src=\"https://ed5bf4f71f.imgdist.com/pub/bfra/qahjrtlh/zep/e62/gec/Colplus.png\" style=\"display: block; height: auto; border: 0; width: 100%;\" width=\"65.5\" alt=\"Your-Logo\" title=\"Your-Logo\" height=\"auto\"></a></div>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "													<table class=\"social_block block-2\" width=\"100%\" border=\"0\" cellpadding=\"10\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\">\r\n"
					+ "																<div class=\"alignment\" align=\"center\">\r\n"
					+ "																	<table class=\"social-table\" width=\"156px\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; display: inline-block;\">\r\n"
					+ "																		<tr>\r\n"
					+ "																			<td style=\"padding:0 10px 0 10px;\"><a href=\"https://www.facebook.com\" target=\"_blank\"><img src=\"https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-circle-white/facebook@2x.png\" width=\"32\" height=\"auto\" alt=\"Facebook\" title=\"facebook\" style=\"display: block; height: auto; border: 0;\"></a></td>\r\n"
					+ "																			<td style=\"padding:0 10px 0 10px;\"><a href=\"https://www.twitter.com\" target=\"_blank\"><img src=\"https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-circle-white/twitter@2x.png\" width=\"32\" height=\"auto\" alt=\"Twitter\" title=\"twitter\" style=\"display: block; height: auto; border: 0;\"></a></td>\r\n"
					+ "																			<td style=\"padding:0 10px 0 10px;\"><a href=\"https://www.instagram.com\" target=\"_blank\"><img src=\"https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-circle-white/instagram@2x.png\" width=\"32\" height=\"auto\" alt=\"Instagram\" title=\"instagram\" style=\"display: block; height: auto; border: 0;\"></a></td>\r\n"
					+ "																		</tr>\r\n"
					+ "																	</table>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "													<table class=\"paragraph_block block-3\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"padding-bottom:15px;padding-left:10px;padding-right:10px;padding-top:15px;\">\r\n"
					+ "																<div style=\"color:#dedede;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;font-size:14px;line-height:120%;text-align:center;mso-line-height-alt:16.8px;\">\r\n"
					+ "																	<p style=\"margin: 0; word-break: break-word;\"><em>2024 © All rights reserved</em></p>\r\n"
					+ "																</div>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n" + "								</td>\r\n"
					+ "							</tr>\r\n" + "						</tbody>\r\n"
					+ "					</table>\r\n"
					+ "					<table class=\"row row-4\" align=\"center\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ffffff;\">\r\n"
					+ "						<tbody>\r\n" + "							<tr>\r\n"
					+ "								<td>\r\n"
					+ "									<table class=\"row-content stack\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #0a0a0a; color: #000000; width: 655px; margin: 0 auto;\" width=\"655\">\r\n"
					+ "										<tbody>\r\n"
					+ "											<tr>\r\n"
					+ "												<td class=\"column column-1\" width=\"100%\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\">\r\n"
					+ "													<table class=\"icons_block block-1\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; text-align: center; line-height: 0;\">\r\n"
					+ "														<tr>\r\n"
					+ "															<td class=\"pad\" style=\"vertical-align: middle; color: #1e0e4b; font-family: 'Inter', sans-serif; font-size: 15px; padding-bottom: 5px; padding-top: 5px; text-align: center;\"><!--[if vml]><table align=\"center\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"display:inline-block;padding-left:0px;padding-right:0px;mso-table-lspace: 0pt;mso-table-rspace: 0pt;\"><![endif]-->\r\n"
					+ "																<!--[if !vml]><!-->\r\n"
					+ "																<table class=\"icons-inner\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; display: inline-block; padding-left: 0px; padding-right: 0px;\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\"><!--<![endif]-->\r\n"
					+ "																	<tr>\r\n"
					+ "																		<td style=\"vertical-align: middle; text-align: center; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 6px;\"><a href=\"http://designedwithbeefree.com/\" target=\"_blank\" style=\"text-decoration: none;\"><img class=\"icon\" alt=\"Beefree Logo\" src=\"https://d1oco4z2z1fhwp.cloudfront.net/assets/Beefree-logo.png\" height=\"auto\" width=\"34\" align=\"center\" style=\"display: block; height: auto; margin: 0 auto; border: 0;\"></a></td>\r\n"
					+ "																		<td style=\"font-family: 'Inter', sans-serif; font-size: 15px; font-weight: undefined; color: #1e0e4b; vertical-align: middle; letter-spacing: undefined; text-align: center; line-height: normal;\"><a href=\"http://designedwithbeefree.com/\" target=\"_blank\" style=\"color: #1e0e4b; text-decoration: none;\">Designed with Beefree</a></td>\r\n"
					+ "																	</tr>\r\n"
					+ "																</table>\r\n"
					+ "															</td>\r\n"
					+ "														</tr>\r\n"
					+ "													</table>\r\n"
					+ "												</td>\r\n"
					+ "											</tr>\r\n"
					+ "										</tbody>\r\n"
					+ "									</table>\r\n" + "								</td>\r\n"
					+ "							</tr>\r\n" + "						</tbody>\r\n"
					+ "					</table>\r\n" + "				</td>\r\n" + "			</tr>\r\n"
					+ "		</tbody>\r\n" + "	</table><!-- End -->\r\n" + "</body>\r\n" + "\r\n" + "</html>";
			helper.setText(htmlMessage, true);
			javaMailSender.send(message);
			return code;
		} catch (MessagingException e) {
			e.printStackTrace();
		}
		return "Email not found";

	}

	public int randomNumberInRange(int minimo, int maximo) {

		return ThreadLocalRandom.current().nextInt(minimo, maximo + 1);
	}

	public String randomString() {
		String banco = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
		String cadena = "";
		int longitud = 20;
		for (int x = 0; x < longitud; x++) {
			int indiceAleatorio = randomNumberInRange(0, banco.length() - 1);
			char caracterAleatorio = banco.charAt(indiceAleatorio);
			cadena += caracterAleatorio;
		}
		return cadena;
	}
}
